name: build
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn --settings settings.xml -B clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

      - name: Sonar with Maven
        run: mvn --settings settings.xml -B sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          docker login docker.pkg.github.com -u rdlopes -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          docker build -t docker.pkg.github.com/rdlopes/nifi-open-nlp/nifi:latest .
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.LOCAL_TOKEN }}
