name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Clean with Maven
        run: mvn -B clean --file pom.xml

      - name: Install with Maven
        run: mvn -B install --file pom.xml

      - name: Sonar with Maven
        run: mvn -B sonar:sonar --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

      - name: Deploy
        run: mvn -B deploy:deploy -Dregistry=https://maven.pkg.github.com/rdlopes/nifi-open-nlp -Dtoken=$GITHUB_TOKEN -f pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

